server:
    port: 8085

spring:
    application:
        name: notification-service

    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: notification-group-v2
            auto-offset-reset: latest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "*"
                spring.json.value.default.type: "com.ra.notificationservice.event.OrderEvent"

    producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
            spring.json.add.type.headers: false